CE103 Algorithms and Programming I HW3: C:/hw3/MedicalStoreManagement/MedicalStoreManagement/MedicalStoreManagement.c File Reference
MedicalStoreManagement.c File Reference
#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <math.h>
#include <dos.h>
#include <time.h>
#include <ctype.h>
#include <windows.h>
Data Structures
struct medical
struct supplier
struct customer
struct bill
struct sales_report
struct purchase_report
struct profit_report
Macros
#define _CRT_SECURE_NO_WARNINGS
Functions
void gotoxy (int x, int y)
int getcust_id ()
int getsupp_id ()
void welcome ()
void main_menu ()
void main_box ()
void box1 ()
void wbox ()
void bill ()
void about ()
void medicine ()
void medi_sale ()
void stock ()
void update_stock ()
void medi_entry ()
void medi_search ()
void remainderQty ()
void supplier ()
void supp_entry ()
void supp_list ()
void sup_update ()
void search ()
void search_id ()
void search_name ()
void customer ()
void cust_search ()
void search_cid ()
void search_cname ()
void cust_entry ()
void cust_list ()
void cust_update ()
void report_menu ()
void report ()
void sale_rpt ()
void sale_rpt_daily ()
void profit_rpt ()
void pur_rpt ()
void pur_rpt_daily ()
void linkfloat ()
int t (void)
void animation ()
void ventry (char t[], int code)
void box ()
void lbox ()
int main ()
Variables
COORD coord = { 0, 0 }
int i
struct medical temp
struct medical x [20]
FILE * ptr
char a [10]
struct supplier temp1
struct customer temp_c
FILE * ptr1
struct bill bil
FILE * ptrbill
struct sales_report s_r
FILE * ptrs_r
struct purchase_report p_r
FILE * ptrp_r
struct profit_report pr_r
FILE * ptrpr_r
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Function Documentation
about()
void about ()
References animation(), gotoxy(), and main_menu().
Referenced by main_menu().
animation()
void animation ()
References gotoxy(), and i.
Referenced by about(), cust_search(), customer(), main_menu(), search(), stock(), and supplier().
bill()
void bill ()
References bil, bill::billno, box(), bill::cname, bill::day, gotoxy(), i, bill::medi_qty, bill::medi_rate, bill::mediname, bill::month, ptrbill, bill::total, and bill::year.
Referenced by main_menu().
box()
void box ()
References gotoxy(), and i.
Referenced by bill(), cust_entry(), cust_list(), cust_update(), medi_entry(), medi_sale(), medi_search(), profit_rpt(), pur_rpt(), pur_rpt_daily(), sale_rpt(), sale_rpt_daily(), search_cid(), search_cname(), search_id(), search_name(), stock(), sup_update(), supp_entry(), supp_list(), and update_stock().
box1()
void box1 ()
References gotoxy(), and i.
Referenced by main_menu().
cust_entry()
void cust_entry ()
References box(), customer::city, customer::cust_id, customer::cust_name, customer::email, exit(), getcust_id(), gotoxy(), lbox(), customer::mob_no, t(), temp_c, and ventry().
Referenced by customer().
cust_list()
void cust_list ()
References box(), customer::city, customer::cust_id, customer::cust_name, customer::email, exit(), gotoxy(), i, lbox(), customer::mob_no, ptr1, and temp_c.
Referenced by customer().
cust_search()
void cust_search ()
References animation(), customer(), gotoxy(), main_box(), search_cid(), and search_cname().
Referenced by customer().
cust_update()
void cust_update ()
References box(), customer::city, customer::cust_id, customer::cust_name, customer::email, exit(), gotoxy(), i, lbox(), customer::mob_no, ptr1, temp_c, and ventry().
Referenced by customer().
customer()
void customer ()
References animation(), cust_entry(), cust_list(), cust_search(), cust_update(), gotoxy(), main_box(), and main_menu().
Referenced by cust_search(), and main_menu().
getcust_id()
int getcust_id ()
References customer::city, customer::cust_id, customer::cust_name, customer::email, gotoxy(), customer::mob_no, and temp_c.
Referenced by cust_entry().
getsupp_id()
int getsupp_id ()
References supplier::city, supplier::email, gotoxy(), supplier::mob_no, supplier::supp_id, supplier::supp_name, and temp1.
Referenced by supp_entry().
gotoxy()
void gotoxy (int x, int y)
References coord, and x.
Referenced by about(), animation(), bill(), box(), box1(), cust_entry(), cust_list(), cust_search(), cust_update(), customer(), getcust_id(), getsupp_id(), lbox(), main_box(), main_menu(), medi_entry(), medi_sale(), medi_search(), medicine(), profit_rpt(), pur_rpt(), pur_rpt_daily(), remainderQty(), report_menu(), sale_rpt(), sale_rpt_daily(), search(), search_cid(), search_cname(), search_id(), search_name(), stock(), sup_update(), supp_entry(), supp_list(), supplier(), t(), update_stock(), wbox(), and welcome().
lbox()
void lbox ()
References gotoxy(), and i.
Referenced by cust_entry(), cust_list(), cust_update(), medi_entry(), medi_search(), profit_rpt(), pur_rpt(), pur_rpt_daily(), sale_rpt(), sale_rpt_daily(), stock(), sup_update(), supp_entry(), and supp_list().
linkfloat()
void linkfloat ()
main()
int main ()
References i, and main_menu().
main_box()
void main_box ()
References gotoxy(), and i.
Referenced by cust_search(), customer(), main_menu(), medicine(), report_menu(), search(), and supplier().
main_menu()
void main_menu ()
References about(), animation(), bill(), box1(), customer(), exit(), gotoxy(), main_box(), main_menu(), medicine(), remainderQty(), report_menu(), supplier(), and t().
Referenced by about(), customer(), d_mainmenu(), main(), main_menu(), medicine(), report_menu(), stock(), and supplier().
medi_entry()
void medi_entry ()
References a, box(), medical::cabnit, medical::comp_name, medical::cost, medical::exp_date, gotoxy(), medical::id, lbox(), medical::manu_date, medi_entry(), purchase_report::medi_id, medical::medi_name, purchase_report::medir_name, p_r, ptr, ptrp_r, purchase_report::qty, medical::quantity, medical::rack, purchase_report::rate, medical::sale, purchase_report::sDay, purchase_report::sMonth, medical::supp_name, purchase_report::supp_name, purchase_report::sYear, t(), temp, medical::total, purchase_report::total, medical::unit, and ventry().
Referenced by medi_entry(), and medicine().
medi_sale()
void medi_sale ()
References a, bil, bill::billno, box(), medical::bye, customer::city, bill::cname, medical::cost, customer::cust_id, customer::cust_name, sales_report::cust_name, bill::day, customer::email, gotoxy(), i, medical::id, sales_report::medi_id, profit_report::medi_id, medical::medi_name, bill::medi_qty, bill::medi_rate, bill::mediname, sales_report::medir_name, profit_report::medir_name, customer::mob_no, bill::month, pr_r, profit_report::profit, ptr, ptr1, ptrpr_r, ptrs_r, medical::qty, sales_report::qty, profit_report::qty, medical::quantity, sales_report::rate, profit_report::rate, s_r, medical::sale, sales_report::sDay, profit_report::sDay, sales_report::sMonth, profit_report::sMonth, sales_report::sYear, profit_report::sYear, t(), temp, temp_c, medical::total, bill::total, sales_report::total, medical::unit, profit_report::unit, ventry(), x, and bill::year.
Referenced by medicine().
medi_search()
void medi_search ()
References box(), exit(), medical::exp_date, gotoxy(), i, medical::id, lbox(), medical::medi_name, ptr1, medical::quantity, medical::supp_name, and temp.
Referenced by medicine().
medicine()
void medicine ()
References gotoxy(), main_box(), main_menu(), medi_entry(), medi_sale(), medi_search(), and stock().
Referenced by main_menu().
profit_rpt()
void profit_rpt ()
References box(), gotoxy(), lbox(), profit_report::medi_id, profit_report::medir_name, pr_r, profit_report::profit, ptrpr_r, profit_report::qty, profit_report::rate, profit_report::sDay, profit_report::sMonth, profit_report::sYear, t(), and profit_report::unit.
Referenced by report_menu().
pur_rpt()
void pur_rpt ()
References box(), exit(), gotoxy(), lbox(), purchase_report::medi_id, purchase_report::medir_name, p_r, ptrp_r, purchase_report::qty, purchase_report::rate, purchase_report::sDay, purchase_report::sMonth, purchase_report::supp_name, purchase_report::sYear, t(), and purchase_report::total.
Referenced by report_menu().
pur_rpt_daily()
void pur_rpt_daily ()
References box(), exit(), gotoxy(), lbox(), purchase_report::medi_id, purchase_report::medir_name, p_r, ptrp_r, purchase_report::qty, purchase_report::rate, purchase_report::sDay, purchase_report::sMonth, purchase_report::supp_name, purchase_report::sYear, t(), and purchase_report::total.
Referenced by report_menu().
remainderQty()
void remainderQty ()
References gotoxy(), medical::medi_name, ptr1, medical::quantity, and temp.
Referenced by main_menu().
report()
void report ()
report_menu()
void report_menu ()
References gotoxy(), main_box(), main_menu(), profit_rpt(), pur_rpt(), pur_rpt_daily(), sale_rpt(), and sale_rpt_daily().
Referenced by main_menu().
sale_rpt()
void sale_rpt ()
References box(), sales_report::cust_name, exit(), gotoxy(), lbox(), sales_report::medi_id, sales_report::medir_name, ptrs_r, sales_report::qty, sales_report::rate, s_r, sales_report::sDay, sales_report::sMonth, sales_report::sYear, and sales_report::total.
Referenced by report_menu().
sale_rpt_daily()
void sale_rpt_daily ()
References box(), sales_report::cust_name, exit(), gotoxy(), lbox(), sales_report::medi_id, sales_report::medir_name, ptrs_r, sales_report::qty, sales_report::rate, s_r, sales_report::sDay, sales_report::sMonth, sales_report::sYear, and sales_report::total.
Referenced by report_menu().
search()
void search ()
References animation(), gotoxy(), main_box(), search_id(), search_name(), and supplier().
Referenced by supplier().
search_cid()
void search_cid ()
References box(), customer::city, customer::cust_id, customer::cust_name, customer::email, gotoxy(), i, customer::mob_no, ptr1, and temp_c.
Referenced by cust_search().
search_cname()
void search_cname ()
References box(), customer::city, customer::cust_id, customer::cust_name, customer::email, gotoxy(), i, customer::mob_no, ptr1, and temp_c.
Referenced by cust_search().
search_id()
void search_id ()
References box(), supplier::city, supplier::email, gotoxy(), i, supplier::mob_no, supplier::supp_id, supplier::supp_name, and temp1.
Referenced by search().
search_name()
void search_name ()
References box(), supplier::city, supplier::email, gotoxy(), i, supplier::mob_no, ptr1, supplier::supp_id, supplier::supp_name, and temp1.
Referenced by search().
stock()
void stock ()
References animation(), box(), exit(), medical::exp_date, gotoxy(), i, medical::id, lbox(), main_menu(), medical::medi_name, ptr1, medical::quantity, medical::supp_name, temp, and update_stock().
Referenced by medicine().
sup_update()
void sup_update ()
References box(), supplier::city, supplier::email, exit(), gotoxy(), i, lbox(), supplier::mob_no, ptr1, supplier::supp_id, supplier::supp_name, temp1, and ventry().
Referenced by supplier().
supp_entry()
void supp_entry ()
References box(), supplier::city, supplier::email, exit(), getsupp_id(), gotoxy(), lbox(), supplier::mob_no, supplier::supp_id, supplier::supp_name, t(), temp1, and ventry().
Referenced by supplier().
supp_list()
void supp_list ()
References box(), supplier::city, supplier::email, exit(), gotoxy(), i, lbox(), supplier::mob_no, ptr1, supplier::supp_id, supplier::supp_name, t(), and temp1.
Referenced by supplier().
supplier()
void supplier ()
References animation(), gotoxy(), main_box(), main_menu(), search(), sup_update(), supp_entry(), and supp_list().
Referenced by main_menu(), and search().
t()
int t (void)
References gotoxy(), and t().
Referenced by cust_entry(), main_menu(), medi_entry(), medi_sale(), profit_rpt(), pur_rpt(), pur_rpt_daily(), supp_entry(), supp_list(), t(), and ventry().
update_stock()
void update_stock ()
References a, box(), medical::bye, medical::cost, exit(), gotoxy(), i, medical::id, medical::medi_name, ptr, medical::qty, medical::quantity, medical::sale, temp, medical::total, medical::unit, and x.
Referenced by stock().
ventry()
void ventry (char t[], int code)
References i, and t().
Referenced by cust_entry(), cust_update(), medi_entry(), medi_sale(), sup_update(), and supp_entry().
wbox()
void wbox ()
References gotoxy(), and i.
Referenced by welcome().
welcome()
void welcome ()
References gotoxy(), i, and wbox().
Variable Documentation
a
char a[10]
Referenced by d_quan(), d_rate(), medi_entry(), medi_sale(), update_stock(), and window().
bil
struct bill bil
Referenced by bill(), and medi_sale().
coord
COORD coord = { 0, 0 }
Referenced by gotoxy().
i
int i
Referenced by animation(), bill(), box(), box1(), cust_list(), cust_update(), d_all(), d_code(), d_mainmenu(), d_quan(), d_rate(), d_search(), dbill(), dis_con(), display(), lbox(), main(), main_box(), medi_sale(), medi_search(), search_cid(), search_cname(), search_id(), search_name(), stock(), sup_update(), supp_list(), update_stock(), ventry(), wbox(), welcome(), and window().
p_r
struct purchase_report p_r
Referenced by medi_entry(), pur_rpt(), and pur_rpt_daily().
pr_r
struct profit_report pr_r
Referenced by medi_sale(), and profit_rpt().
ptr
FILE* ptr
Referenced by medi_entry(), medi_sale(), and update_stock().
ptr1
FILE* ptr1
Referenced by cust_list(), cust_update(), medi_sale(), medi_search(), remainderQty(), search_cid(), search_cname(), search_name(), stock(), sup_update(), and supp_list().
ptrbill
FILE* ptrbill
Referenced by bill().
ptrp_r
FILE* ptrp_r
Referenced by medi_entry(), pur_rpt(), and pur_rpt_daily().
ptrpr_r
FILE* ptrpr_r
Referenced by medi_sale(), and profit_rpt().
ptrs_r
FILE* ptrs_r
Referenced by medi_sale(), sale_rpt(), and sale_rpt_daily().
s_r
struct sales_report s_r
Referenced by medi_sale(), sale_rpt(), and sale_rpt_daily().
temp
struct medical temp
Referenced by medi_entry(), medi_sale(), medi_search(), remainderQty(), stock(), and update_stock().
temp1
struct supplier temp1
Referenced by getsupp_id(), search_id(), search_name(), sup_update(), supp_entry(), and supp_list().
temp_c
struct customer temp_c
Referenced by cust_entry(), cust_list(), cust_update(), getcust_id(), medi_sale(), search_cid(), and search_cname().
x
struct medical x[20]
Referenced by add(), bill(), check(), d_code(), del(), edit(), gotoxy(), medi_sale(), and update_stock().