#pragma once

//messages are numbered with unique ID and this message translated text are  stored on en.dat and tr.dat files
#define main_menu 1
#define search_menu 2
#define by_code1 3
#define by_rate1 4
#define by_quantity1 5
#define back_to_main_menu1 6
#define by_code2 7
#define by_rate2 8
#define by_quantity2 9
#define back_to_main_menu2 10
#define calculate_bill1 11
#define add_goods1 12
#define edit_goods1 13
#define display_all1 14
#define search1 15
#define delete_goods1 16
#define change_language1 17
#define exit1 18
#define calculate_bill2 19
#define add_goods2 20
#define edit_goods2 21
#define display_all2 22
#define search2 23
#define delete_goods2 24
#define change_language2 25
#define exit2 26
#define enter_end_to_finish_input 27
#define enter_item_code 28
#define enter_quantity 29
#define total_amount 30
#define fashion_wear 31
#define department_store 32
#define customers_bill 33
#define sn_ 34
#define enter_new_record 35
#define enter_rate_of_the_item 36
#define enter_quantity_of_the_item 37
#define enter_name_of_the_item 38
#define enter_new_record_ 39
#define add_articles 40
#define enter_new_code_of_the_article 41
#define code_already_exists 42
#define enter_again 43
#define edit_records 44
#define enter_item_code4 45
#define name1 46
#define code1 47
#define rate1 48
#define quantity1 49
#define do_you_want_to_edit_this_record 50
#define edit_name 51
#define edit_code 52
#define edit_rate 53
#define edit_quantity 54
#define enter_your_choice 55
#define enter_new_name 56
#define enter_new_rate 57
#define enter_new_quantity 58
#define item_edited 59
#define item_does_not_exist 60
#define try_again 61
#define press_any_key_to_see_more 62
#define no_articles_found 63
#define enter_lower_range 64
#define enter_upper_range 65
#define no_items_found 66
#define records 67
#define delete_articles 68
#define item_deleted 69
#define enter_your_choice1 70