CE103 Algorithms and Programming I HW3: C:/hw3/LocalizationExample/LocalizationExample/LocalizationExample.c File Reference
LocalizationExample.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "translate.h"
#include "message.h"
Macros
#define _CRT_SECURE_NO_WARNINGS
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Function Documentation
main()
int main (int argc, char * argv[])
References APP_LANG_TR, current_lang_setting, ENGLISH_L, enter_language_option, getTranslateLang(), lets_translate_messages, printTranslateLang(), setTranslateLang(), TURKISH_L, and welcome_to_my_program.