CE103 Algorithms and Programming I HW3: C:/hw3/DepartmentStoreManagementSystem/DepartmentStoreManagementSystem/DepartmentStoreManagementSystem.c File Reference
DepartmentStoreManagementSystem.c File Reference
#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <windows.h>
#include "translate.h"
#include "message.h"
Data Structures
struct rec
Macros
#define _CRT_SECURE_NO_WARNINGS
#define enter_your_choice1 70
#define ANS 15
#define ACS 4
Functions
void gotoxy (int x, int y)
void c_code (char[])
int check (char[])
void curser (int)
void dbill ()
void d_mainmenu ()
void display (rec *, int, int)
void window (int, int, int, int)
void dis_con ()
void d_search ()
void highlight (int, int)
void bill ()
void edit ()
void add ()
void del ()
void lang ()
void exit ()
void d_code ()
void d_rate ()
void d_quan ()
void d_all ()
int main ()
int check (char x[ANS])
Variables
COORD coord = { 0,0 }
rec item
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
ACS
#define ACS 4
ANS
#define ANS 15
enter_your_choice1
#define enter_your_choice1 70
Function Documentation
add()
void add ()
References ACS, c_code(), rec::code, d_mainmenu(), enter_name_of_the_item, enter_new_record, enter_new_record_, enter_quantity_of_the_item, enter_rate_of_the_item, gotoxy(), item, rec::name, printTranslateLang(), rec::quantity, rec::rate, and x.
Referenced by curser().
bill()
void bill ()
References rec::code, d_mainmenu(), dbill(), enter_end_to_finish_input, enter_item_code, enter_quantity, gotoxy(), i, item, rec::name, printTranslateLang(), rec::quantity, rec::rate, total_amount, and x.
Referenced by curser().
c_code()
void c_code (char y[])
References add_articles, rec::code, code_already_exists, enter_again, enter_new_code_of_the_article, gotoxy(), item, printTranslateLang(), and window().
Referenced by add(), and edit().
check() [1/2]
int check (char x[ANS])
References rec::code, item, and x.
check() [2/2]
int check (char [])
Referenced by del(), and edit().
curser()
void curser (int no)
References add(), bill(), d_all(), d_code(), d_mainmenu(), d_quan(), d_rate(), d_search(), del(), edit(), exit(), gotoxy(), highlight(), and lang().
Referenced by d_mainmenu(), and d_search().
d_all()
void d_all ()
References d_mainmenu(), dis_con(), display(), gotoxy(), i, item, no_articles_found, press_any_key_to_see_more, and printTranslateLang().
Referenced by curser().
d_code()
void d_code ()
References rec::code, d_search(), dis_con(), display(), enter_item_code, gotoxy(), i, item, no_items_found, printTranslateLang(), and x.
Referenced by curser().
d_mainmenu()
void d_mainmenu ()
References curser(), gotoxy(), i, main_menu(), printTranslateLang(), and window().
Referenced by add(), bill(), curser(), d_all(), del(), edit(), lang(), and main().
d_quan()
void d_quan ()
References a, d_search(), dis_con(), display(), enter_lower_range, enter_upper_range, gotoxy(), i, item, no_items_found, press_any_key_to_see_more, printTranslateLang(), and rec::quantity.
Referenced by curser().
d_rate()
void d_rate ()
References a, d_search(), dis_con(), display(), enter_lower_range, enter_upper_range, gotoxy(), i, item, no_items_found, press_any_key_to_see_more, printTranslateLang(), and rec::rate.
Referenced by curser().
d_search()
void d_search ()
References curser(), gotoxy(), i, printTranslateLang(), search_menu, and window().
Referenced by curser(), d_code(), d_quan(), and d_rate().
dbill()
void dbill ()
References customers_bill, department_store, fashion_wear, gotoxy(), i, printTranslateLang(), and sn_.
Referenced by bill().
del()
void del ()
References ANS, check(), rec::code, d_mainmenu(), delete_articles, enter_item_code, gotoxy(), item, item_deleted, item_does_not_exist, printTranslateLang(), try_again, window(), and x.
Referenced by curser().
dis_con()
void dis_con ()
References department_store, fashion_wear, gotoxy(), i, printTranslateLang(), records, and sn_.
Referenced by d_all(), d_code(), d_quan(), and d_rate().
display()
void display (rec * item, int i, int j)
References rec::code, gotoxy(), i, item, rec::name, rec::quantity, and rec::rate.
Referenced by d_all(), d_code(), d_quan(), and d_rate().
edit()
void edit ()
References ACS, c_code(), check(), rec::code, code1, d_mainmenu(), do_you_want_to_edit_this_record, edit_code, edit_name, edit_quantity, edit_rate, edit_records, enter_item_code4, enter_new_name, enter_new_quantity, enter_new_rate, enter_your_choice, gotoxy(), item, item_does_not_exist, item_edited, rec::name, name1, printTranslateLang(), rec::quantity, quantity1, rec::rate, rate1, try_again, window(), and x.
Referenced by curser().
exit()
void exit ()
Referenced by curser(), cust_entry(), cust_list(), cust_update(), main_menu(), medi_search(), printTranslateLang(), pur_rpt(), pur_rpt_daily(), sale_rpt(), sale_rpt_daily(), stock(), sup_update(), supp_entry(), supp_list(), and update_stock().
gotoxy()
void gotoxy (int x, int y)
References coord, and x.
Referenced by add(), bill(), c_code(), curser(), d_all(), d_code(), d_mainmenu(), d_quan(), d_rate(), d_search(), dbill(), del(), dis_con(), display(), edit(), highlight(), lang(), and window().
highlight()
void highlight (int no, int count)
References add_goods1, add_goods2, back_to_main_menu1, back_to_main_menu2, by_code1, by_code2, by_quantity1, by_quantity2, by_rate1, by_rate2, calculate_bill1, calculate_bill2, change_language1, change_language2, delete_goods1, delete_goods2, display_all1, display_all2, edit_goods1, edit_goods2, exit1, exit2, gotoxy(), printTranslateLang(), search1, and search2.
Referenced by curser().
lang()
void lang ()
References APP_LANG_TR, change_language1, d_mainmenu(), ENGLISH_L, enter_your_choice1, gotoxy(), printTranslateLang(), setTranslateLang(), TURKISH_L, and window().
Referenced by curser(), and getTranslateLang().
main()
int main ()
References d_mainmenu(), getTranslateLang(), and setTranslateLang().
window()
void window (int a, int b, int c, int d)
References a, department_store, fashion_wear, gotoxy(), i, and printTranslateLang().
Referenced by c_code(), d_mainmenu(), d_search(), del(), edit(), and lang().
Variable Documentation
coord
COORD coord = { 0,0 }
Referenced by gotoxy().
item
rec item
Referenced by add(), bill(), c_code(), check(), d_all(), d_code(), d_quan(), d_rate(), del(), display(), and edit().